Repository danielz02/Office-Hour-125, pull requests merged in 2019-12, with the labels that each got.

#2 Add logic for QueueInfo and polymorphism
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Family125.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/MainActivity.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Queue.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/QueueInfo.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Student.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Summary.java
Labels: good first issue

#3 Add Code for Office Hour Summary and Fix Bugs with UI
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/CA.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/OfficeHourSummary.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Queue.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Student.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Summary.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/home/HomeFragment.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#4 Ui
  app/src/main/AndroidManifest.xml
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/home/HomeFragment.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/queue/QueueActivity.java
  app/src/main/res/layout/chunk_task.xml
  app/src/main/res/layout/fragment_queue.xml
  app/src/main/res/layout/queue_request.xml
  app/src/main/res/layout/staff_portal.xml
Labels: enhancement

#5 Add new features for queue
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Family125.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/OfficeHourSummary.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Queue.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/QueueInfo.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Student.java
Labels: bug, enhancement

#6 Backend branch
  app/src/main/AndroidManifest.xml
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Family125.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/MainActivity.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/OfficeHourStatus.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/QueueInfo.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Student.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Summary.java
Labels: enhancement

#7 Bug fix and new feature for CA class
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/CA.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Family125.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/MainActivity.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Student.java
Labels: bug, enhancement

#8 New UI features
  app/src/main/AndroidManifest.xml
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Student.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/StaffPortal.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/home/HomeFragment.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/queue/QueueActivity.java
  app/src/main/res/layout/queue_request.xml
Labels: enhancement

#9 Add calendar and bug fix
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/CA.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Family125.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/MainActivity.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/QueueInfo.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Student.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/home/HomeFragment.java
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#11 Add UI logic for the presence at office hour
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/home/HomeFragment.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/queue/QueueActivity.java
  app/src/main/res/layout/fragment_home.xml
Labels: bug, enhancement

#12 Bug Hotfix
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/QueueInfo.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Student.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/queue/QueueActivity.java
Labels: enhancement

#13 Fix bug in exit button
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Student.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/home/HomeFragment.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/queue/QueueActivity.java
Labels: enhancement

#14 Bug Hotfix
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/home/HomeFragment.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/queue/QueueActivity.java
  app/src/main/res/layout/fragment_home.xml
Labels: enhancement

#16 Enhance getInstance() and add code for fetching gravatar
  app/build.gradle
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/CA.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Family125.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/MD5Util.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/MainActivity.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/Student.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/home/HomeFragment.java
  app/src/main/res/layout/nav_header_main.xml
Labels: bug, enhancement

#18 Add UI for At 0403
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/home/HomeFragment.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/tools/ToolsFragment.java
  app/src/main/res/layout/chunk_at403.xml
  app/src/main/res/layout/fragment_tools.xml
Labels: enhancement

#19 Add TA/CA Forecast and In-app Email
  app/build.gradle
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/CA.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/forecast/ForecastFragment.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/home/HomeFragment.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/tools/ToolsFragment.java
  app/src/main/res/layout/chunk_at403.xml
  app/src/main/res/layout/fragment_forecast.xml
  app/src/main/res/layout/fragment_tools.xml
Labels: enhancement

#20 Add logic for CA task assignment
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/StaffPortal.java
  app/src/main/res/layout/app_bar_main.xml
  app/src/main/res/layout/chunk_task.xml
  app/src/main/res/layout/staff_portal.xml
Labels: enhancement

#22 Add new features for notification and stress relief
  app/build.gradle
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/CA.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/MainActivity.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/StaffPortal.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/fun/FunFragment.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/fun/FunViewModel.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/home/HomeFragment.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/queue/QueueFragment.java
  app/src/main/java/edu/illinois/cs/cs125/fall2019/oh125/ui/share/ShareFragment.java
  app/src/main/res/layout/chunk_queue.xml
  app/src/main/res/layout/fragment_fun.xml
  app/src/main/res/layout/fragment_queue.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
